In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('teams.csv')
df.head()

  team  year  athletes  events   age  height  weight  prev_medals  medals
0  AFG  1964         8       8  22.0   161.0    64.2          0.0       0
1  AFG  1968         5       5  23.2   170.2    70.0          0.0       0
2  AFG  1972         8       8  29.0   168.3    63.8          0.0       0
3  AFG  1980        11      11  23.6   168.4    63.2          0.0       0
4  AFG  2004         5       5  18.6   170.8    64.8          0.0       0

In [3]:
df.isna().sum()

team           0
year           0
athletes       0
events         0
age            0
height         0
weight         0
prev_medals    0
medals         0
dtype: int64

In [4]:
train, test = train_test_split(df, test_size=.2, random_state=42)

In [5]:
predictors = ['athletes', 'events']
target = ['medals']

In [6]:
X = train[predictors].copy()
y = train[target].copy()

In [7]:
X.describe()

          athletes       events
count  1611.000000  1611.000000
mean     77.337678    37.115456
std     132.404214    50.993621
min       1.000000     1.000000
25%       7.000000     6.000000
50%      21.000000    14.000000
75%      74.000000    47.000000
max     839.000000   270.000000

In [8]:
X = (X - X.mean()) / X.std()

In [9]:
X.describe()

           athletes        events
count  1.611000e+03  1.611000e+03
mean  -2.425813e-17 -5.513212e-17
std    1.000000e+00  1.000000e+00
min   -5.765502e-01 -7.082348e-01
25%   -5.312344e-01 -6.101833e-01
50%   -4.254976e-01 -4.533009e-01
75%   -2.520825e-02  1.938388e-01
max    5.752553e+00  4.566935e+00

In [10]:
X['intercept'] = 1
X = X[['intercept'] + predictors]

In [11]:
alpha = 2
I = np.eye(X.shape[1])

In [12]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
I[0 ,0] = 0

In [14]:
penalty = alpha * I

In [15]:
B = np.linalg.inv(X.T @ X + penalty) @ X.T @ y

In [16]:
B

      medals
0  11.459963
1  66.862969
2 -38.134052

In [ ]:
test_X = test[predictors]